//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCUMENTO()
        {
            this.DOCUMENTO_PESQUISA = new HashSet<DOCUMENTO_PESQUISA>();
        }
    
        public int DOCU_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int CLAS_CD_ID { get; set; }
        public Nullable<int> CADO_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public string DOCU_NM_NOME { get; set; }
        public System.DateTime DOCU_DT_CADASTRO { get; set; }
        public string DOCU_AQ_ARQUIVO { get; set; }
        public Nullable<int> DOCU_IN_FORMATO { get; set; }
        public string DOCU_DS_DESCRICAO { get; set; }
        public Nullable<int> DOCU_IN_DOWNLOADS { get; set; }
        public Nullable<int> DOCU_IN_VISUALIZACOES { get; set; }
        public string DOCU_TX_OCR { get; set; }
        public int DOCU_IN_ATIVO { get; set; }
        public string DOCU_TX_OBSERVACOES { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CLASSE CLASSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO_PESQUISA> DOCUMENTO_PESQUISA { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
