//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class METADADO_CLASSE
    {
        public int MECL_CD_ID { get; set; }
        public int CLAS_CD_ID { get; set; }
        public string MECL_NM_NOME { get; set; }
        public string MECL_SG_SIGLA { get; set; }
        public string MECL_DS_DESCRICAO { get; set; }
        public Nullable<int> MECL_IN_MULTIVALORADO { get; set; }
        public Nullable<int> TIME_CD_ID { get; set; }
        public Nullable<int> MECL_NR_TAMANHO { get; set; }
        public Nullable<int> MECL_IN_OBRIGATORIO { get; set; }
        public Nullable<int> MECL_IN_INDEXADO { get; set; }
        public int MECK_IN_ATIVO { get; set; }
    
        public virtual CLASSE CLASSE { get; set; }
        public virtual TIPO_METADADO TIPO_METADADO { get; set; }
    }
}
